export NEXUS_HOST=ec2-34-214-159-29.us-west-2.compute.amazonaws.com
export NEXUS=http://${NEXUS_HOST}:8081
export NEXUS_USER=pythondev1
export NEXUS_PASSWORD=password
export NEXUS_INTERNAL_REPO=pypi-internal
export NEXUS_GROUP_REPO=pypi-all
export USERNAME="Mykel Alvis"
export USEREMAIL="mykel.alvis@gmail.com"
export NEXUS_MAVEN_USER=mavendev1
export NEXUS_MAVEN_PASSWORD=password
